name: Iris_MLOps_CI_CD

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model and Generate Reports
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train_model.py
          python testing.py
          echo "### Model Training and Evaluation Report" > report2.md
          cat test.txt >> report2.md
          echo "### RF & LR Model Score" > report.md
          cat scores.txt >> report.md
          echo "### Confusion Matrix & Feature Importance" > report1.md
          echo '![](./Confusion_matrix.png "Confusion Matrix")' >> report1.md
          echo '![](./Feature_importance.png "Feature Importance")' >> report1.md
          cat  report2.md report.md report1.md > CombinedFile.md

      - uses: iterative/setup-cml@v2
        with:
          version: v0.18.1

      - name: Post CML Report
        run: cml comment create CombinedFile.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}